schemaVersion: 2.1.0
metadata:
  name: developer-images
attributes:
  controller.devfile.io/scc: container-build
components:
  - name: devtools
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.9
      memoryRequest: 256Mi
